language: objective-c
osx_image: xcode7.3
before_install:
- brew update
script: xctool -project Prototype02052016.xcodeproj -scheme Prototype02052016 -sdk iphonesimulator test -freshSimulator -freshInstall